# Automatically generated by configure - do not modify
TARGET_NAME=riscv64
CONFIG_SOFTMMU=y
QEMU=$(BUILD_DIR)/riscv64-softmmu/qemu-system-riscv64
CROSS_CC_GUEST_CFLAGS=
DOCKER_IMAGE=debian-riscv64-cross
DOCKER_CROSS_CC_GUEST=riscv64-linux-gnu-gcc
